### ISSUE TITLE
DO NOT RUN! - This is not official code and is "stolen" from PappyG

### ISSUE THREAD

**Issue by JustPandaPan** [HandyCoder01/reaper-phasmophobia#1]
This is just ripped from ['PhasmoMenu By PappyG' on the UnknownCheats.me forums](https://www.unknowncheats.me/forum/phasmophobia/485776-phasmomenu-pappyg.html).

This is not even the latest version. Currently, the newest version is v0.5.1.2
Please use the [official release](https://www.unknowncheats.me/forum/phasmophobia/485776-phasmomenu-pappyg.html) instead of this outdated skid version.

**Also:
1. The project and software are stolen.
2. All code is very obfuscated.
3. Malware-like behavior.
4. Runs background tasks like PowerShell scripts.**

**Comment by HandyCoder01** [comment]
Never said the project is fully mine, the code is really from PappyG's source but I made it a bit different on a few ways. The file itself uses a custom model type of injection to make sure phasmo not able to detect it. Its true now there is no anticheat or I was not able to find any, but in the future that thing is usefull. The powershell script is needed for the injection, its similar to extreme injector's advanced injection.
